(()=>{'use strict';
const S={K:'♔',Q:'♕',R:'♖',B:'♗',N:'♘',P:'♙',k:'♚',q:'♛',r:'♜',b:'♝',n:'♞',p:'♟'},F='abcdefgh';
const ST={opening:{fen:'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',label:'OPENING',status:'오프닝 · 중앙을 장악하세요',main:'먼저 중앙을 차지하고 작은 기물부터 꺼내세요.',sub:'e·d 폰, 나이트, 비숍, 캐슬링이라는 자연스러운 리듬을 만들어 보세요.'},middlegame:{fen:'r1bq1rk1/ppp2ppp/2np1n2/2b1p3/2B1P3/2NP1N2/PPP2PPP/R1BQ1RK1 w - - 4 7',label:'MIDDLEGAME',status:'미들게임 · 강제수부터 확인하세요',main:'Checks → Captures → Threats 순서로 후보수를 훑어보세요.',sub:'왕의 안전과 가장 활동이 나쁜 기물을 함께 확인합니다.'},endgame:{fen:'8/5pk1/4p1p1/8/3P4/4P1P1/5PK1/3R4 w - - 0 1',label:'ENDGAME',status:'엔드게임 · 왕과 패스폰의 거리를 재세요',main:'엔드게임에서는 왕도 공격 기물입니다.',sub:'폰을 밀기 전에 왕의 거리와 룩의 위치를 먼저 확인하세요.'}};
const REF=window.FOR_MY_CHESS_REFERENCE||{openings:[],referenceNotes:[],source:{}};
const $=id=>document.getElementById(id),board=$('board'),frame=$('boardFrame'),stage=$('stage'),diff=$('difficulty'),thinking=$('thinking'),toast=$('toast'),mate=$('mate');
const SAVE_KEY='formychess.games.v1',DRAFT_KEY='formychess.draft.v1';
let st,sel=null,selMoves=[],cur='opening',hist=[],last=null,busy=false,over=false,timer,session=null,referenceBook=new Map();
const alg=i=>F[i%8]+(8-Math.floor(i/8)),idx=a=>(8-Number(a[1]))*8+F.indexOf(a[0]),row=i=>Math.floor(i/8),col=i=>i%8,inside=(r,c)=>r>=0&&r<8&&c>=0&&c<8,white=p=>p&&p===p.toUpperCase(),side=p=>white(p)?'w':'b',opp=s=>s==='w'?'b':'w';
const pad=n=>String(n).padStart(2,'0');
const nowId=()=>{const d=new Date();return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}-${pad(d.getHours())}${pad(d.getMinutes())}${pad(d.getSeconds())}-${Math.random().toString(36).slice(2,7)}`};
function fen(x){let [pos,turn,castle,ep,h='0',f='1']=x.split(' '),b=Array(64).fill(null),i=0;for(const c of pos){if(c==='/')continue;if(/\d/.test(c))i+=+c;else b[i++]=c}return{board:b,turn,castle:castle==='-'?'':castle,ep:ep==='-'?null:idx(ep),half:+h,full:+f}}
function fenString(s){let out='';for(let r=0;r<8;r++){let empty=0;for(let c=0;c<8;c++){const p=s.board[r*8+c];if(!p){empty++;continue}if(empty){out+=empty;empty=0}out+=p}if(empty)out+=empty;if(r<7)out+='/'}return `${out} ${s.turn} ${s.castle||'-'} ${s.ep==null?'-':alg(s.ep)} ${s.half} ${s.full}`}
function clone(s){return{board:s.board.slice(),turn:s.turn,castle:s.castle,ep:s.ep,half:s.half,full:s.full}}
function move(s,m){const n=clone(s),p=n.board[m.from],cap=n.board[m.to];n.board[m.from]=null;n.board[m.to]=m.promotion?(side(p)==='w'?m.promotion.toUpperCase():m.promotion):p;if(m.ep)n.board[m.to+(side(p)==='w'?8:-8)]=null;if(m.castle==='K'){n.board[63]=null;n.board[61]='R'}if(m.castle==='Q'){n.board[56]=null;n.board[59]='R'}if(m.castle==='k'){n.board[7]=null;n.board[5]='r'}if(m.castle==='q'){n.board[0]=null;n.board[3]='r'}const a=alg(m.from),z=alg(m.to);if(p==='K')n.castle=n.castle.replace(/[KQ]/g,'');if(p==='k')n.castle=n.castle.replace(/[kq]/g,'');if(a==='a1'||z==='a1')n.castle=n.castle.replace('Q','');if(a==='h1'||z==='h1')n.castle=n.castle.replace('K','');if(a==='a8'||z==='a8')n.castle=n.castle.replace('q','');if(a==='h8'||z==='h8')n.castle=n.castle.replace('k','');n.ep=null;if(p&&p.toLowerCase()==='p'&&Math.abs(m.to-m.from)===16)n.ep=(m.from+m.to)/2;n.half=(p&&p.toLowerCase()==='p')||cap||m.ep?0:n.half+1;if(s.turn==='b')n.full++;n.turn=opp(s.turn);return n}
function attacked(s,q,by){const r=row(q),c=col(q),b=s.board,p=by==='w'?'P':'p',pr=r+(by==='w'?1:-1);for(const dc of[-1,1])if(inside(pr,c+dc)&&b[pr*8+c+dc]===p)return true;const n=by==='w'?'N':'n';for(const[dr,dc]of[[-2,-1],[-2,1],[-1,-2],[-1,2],[1,-2],[1,2],[2,-1],[2,1]])if(inside(r+dr,c+dc)&&b[(r+dr)*8+c+dc]===n)return true;const k=by==='w'?'K':'k';for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++)if((dr||dc)&&inside(r+dr,c+dc)&&b[(r+dr)*8+c+dc]===k)return true;const bi=by==='w'?'B':'b',ro=by==='w'?'R':'r',qu=by==='w'?'Q':'q';for(const[dr,dc,types]of[[-1,-1,[bi,qu]],[-1,1,[bi,qu]],[1,-1,[bi,qu]],[1,1,[bi,qu]],[-1,0,[ro,qu]],[1,0,[ro,qu]],[0,-1,[ro,qu]],[0,1,[ro,qu]]]){let rr=r+dr,cc=c+dc;while(inside(rr,cc)){const x=b[rr*8+cc];if(x){if(types.includes(x))return true;break}rr+=dr;cc+=dc}}return false}
const king=(s,c)=>s.board.indexOf(c==='w'?'K':'k'),check=(s,c)=>{const k=king(s,c);return k>=0&&attacked(s,k,opp(c))};
function pseudo(s,c){const out=[],b=s.board,push=(from,to,x={})=>{if(to<0||to>63)return;const t=b[to];if(t&&side(t)===c)return;out.push({from,to,...x})};for(let i=0;i<64;i++){const p=b[i];if(!p||side(p)!==c)continue;const t=p.toLowerCase(),r=row(i),cc=col(i);if(t==='p'){const d=c==='w'?-1:1,start=c==='w'?6:1,promo=c==='w'?0:7,r1=r+d;if(inside(r1,cc)&&!b[r1*8+cc]){const to=r1*8+cc;push(i,to,r1===promo?{promotion:'q'}:{});const r2=r+2*d;if(r===start&&!b[r2*8+cc])push(i,r2*8+cc)}for(const dc of[-1,1]){const c2=cc+dc;if(!inside(r1,c2))continue;const to=r1*8+c2;if(b[to]&&side(b[to])!==c)push(i,to,r1===promo?{promotion:'q'}:{});else if(s.ep===to)push(i,to,{ep:true})}}else if(t==='n'){for(const[dr,dc]of[[-2,-1],[-2,1],[-1,-2],[-1,2],[1,-2],[1,2],[2,-1],[2,1]])if(inside(r+dr,cc+dc))push(i,(r+dr)*8+cc+dc)}else if('brq'.includes(t)){const ds=[];if(t==='b'||t==='q')ds.push([-1,-1],[-1,1],[1,-1],[1,1]);if(t==='r'||t==='q')ds.push([-1,0],[1,0],[0,-1],[0,1]);for(const[dr,dc]of ds){let rr=r+dr,c2=cc+dc;while(inside(rr,c2)){const to=rr*8+c2;if(!b[to])push(i,to);else{if(side(b[to])!==c)push(i,to);break}rr+=dr;c2+=dc}}}else if(t==='k'){for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++)if((dr||dc)&&inside(r+dr,cc+dc))push(i,(r+dr)*8+cc+dc);if(!check(s,c)){if(c==='w'&&i===60){if(s.castle.includes('K')&&!b[61]&&!b[62]&&b[63]==='R'&&!attacked(s,61,'b')&&!attacked(s,62,'b'))push(i,62,{castle:'K'});if(s.castle.includes('Q')&&!b[59]&&!b[58]&&!b[57]&&b[56]==='R'&&!attacked(s,59,'b')&&!attacked(s,58,'b'))push(i,58,{castle:'Q'})}if(c==='b'&&i===4){if(s.castle.includes('k')&&!b[5]&&!b[6]&&b[7]==='r'&&!attacked(s,5,'w')&&!attacked(s,6,'w'))push(i,6,{castle:'k'});if(s.castle.includes('q')&&!b[3]&&!b[2]&&!b[1]&&b[0]==='r'&&!attacked(s,3,'w')&&!attacked(s,2,'w'))push(i,2,{castle:'q'})}}}}return out}
const legal=(s,c=s.turn)=>pseudo(s,c).filter(m=>!check(move({...s,turn:c},m),c));
function notation(s,m){const p=s.board[m.from];if(m.castle)return m.castle.toLowerCase()==='q'?'O-O-O':'O-O';const cap=!!s.board[m.to]||m.ep,pc=p.toLowerCase()==='p'?'':p.toUpperCase(),ff=p.toLowerCase()==='p'&&cap?F[col(m.from)]:'';const n=move(s,m),suf=check(n,n.turn)?(legal(n,n.turn).length?'+':'#'):'';return pc+ff+(cap?'x':'')+alg(m.to)+(m.promotion?'=Q':'')+suf}
const uci=m=>alg(m.from)+alg(m.to)+(m.promotion||'');
function moveFromUci(s,u){if(!u||u.length<4)return null;const from=idx(u.slice(0,2)),to=idx(u.slice(2,4)),pr=u[4];return legal(s,s.turn).find(m=>m.from===from&&m.to===to&&(!pr||m.promotion===pr))||null}
function positionKey(s){return s.board.map(p=>p||'.').join('')+'|'+s.turn+'|'+(s.castle||'-')+'|'+(s.ep==null?'-':s.ep)}
function compileReferenceBook(){referenceBook=new Map();for(const line of REF.openings||[]){let s=fen(ST.opening.fen);for(const token of String(line.moves||'').trim().split(/\s+/)){if(!token)continue;const m=moveFromUci(s,token);if(!m)break;if(s.turn==='b'){const key=positionKey(s),arr=referenceBook.get(key)||[];arr.push({uci:token,name:line.name,eco:line.eco,weight:line.weight||1,source:REF.source?.name||'reference'});referenceBook.set(key,arr)}s=move(s,m)}}}
function weightedPick(xs){let total=xs.reduce((a,x)=>a+(x.weight||1),0),r=Math.random()*total;for(const x of xs){r-=x.weight||1;if(r<=0)return x}return xs[xs.length-1]}
function referenceMove(s){if(cur!=='opening')return null;const entries=referenceBook.get(positionKey(s));if(!entries?.length)return null;const legalMoves=legal(s,s.turn),valid=entries.map(e=>({e,m:legalMoves.find(m=>uci(m)===e.uci)})).filter(x=>x.m);if(!valid.length)return null;const pick=weightedPick(valid.map(x=>({...x,weight:x.e.weight})));pick.m.reference=pick.e;return pick.m}
const V={p:100,n:320,b:335,r:500,q:900,k:20000},CENTER=new Set([27,28,35,36]),EXT_CENTER=new Set([18,19,20,21,26,29,34,37,42,43,44,45]);
function pawnStructure(s,c){const pawn=c==='w'?'P':'p',files=Array(8).fill(0);for(let i=0;i<64;i++)if(s.board[i]===pawn)files[col(i)]++;let score=0;for(let f=0;f<8;f++){if(files[f]>1)score-=14*(files[f]-1);if(files[f]&&!(files[f-1]||files[f+1]))score-=8*files[f]}return score}
function rookActivity(s,c){const rook=c==='w'?'R':'r',pawn=c==='w'?'P':'p';let out=0;for(let i=0;i<64;i++)if(s.board[i]===rook){let ownPawn=false,anyPawn=false;for(let r=0;r<8;r++){const p=s.board[r*8+col(i)];if(p&&p.toLowerCase()==='p')anyPawn=true;if(p===pawn)ownPawn=true}if(!ownPawn)out+=anyPawn?10:18}return out}
function evalPos(s){let v=0,nonPawn=0,wB=0,bB=0;for(let i=0;i<64;i++){const p=s.board[i];if(!p)continue;const sg=white(p)?1:-1,t=p.toLowerCase();v+=sg*V[t];if(t!=='p'&&t!=='k')nonPawn+=V[t];if(t==='b'){if(sg>0)wB++;else bB++}if(CENTER.has(i))v+=sg*(t==='p'?24:18);else if(EXT_CENTER.has(i))v+=sg*7;if(t==='p'){const advance=white(p)?6-row(i):row(i)-1;v+=sg*Math.max(0,advance)*5}if('nb'.includes(t)){const d=Math.abs(3.5-row(i))+Math.abs(3.5-col(i));v+=sg*Math.round((7-d)*2.4)}}if(wB>=2)v+=25;if(bB>=2)v-=25;v+=pawnStructure(s,'w')-pawnStructure(s,'b');v+=rookActivity(s,'w')-rookActivity(s,'b');const wMob=pseudo(s,'w').length,bMob=pseudo(s,'b').length;v+=(wMob-bMob)*2;const wDev=(s.board[57]!=='N'?10:0)+(s.board[62]!=='N'?10:0)+(s.board[58]!=='B'?8:0)+(s.board[61]!=='B'?8:0),bDev=(s.board[1]!=='n'?10:0)+(s.board[6]!=='n'?10:0)+(s.board[2]!=='b'?8:0)+(s.board[5]!=='b'?8:0);v+=wDev-bDev;if(s.full<8){if(s.board[59]!=='Q')v-=12;if(s.board[3]!=='q')v+=12}if([62,58].includes(king(s,'w')))v+=28;if([6,2].includes(king(s,'b')))v-=28;if(check(s,'w'))v-=22;if(check(s,'b'))v+=22;if(nonPawn<2600){const wk=king(s,'w'),bk=king(s,'b');if(wk>=0)v+=Math.round((7-(Math.abs(3.5-row(wk))+Math.abs(3.5-col(wk))))*5);if(bk>=0)v-=Math.round((7-(Math.abs(3.5-row(bk))+Math.abs(3.5-col(bk))))*5)}return v}
function moveOrderScore(s,m){const victim=s.board[m.to],attacker=s.board[m.from];let sc=0;if(victim)sc+=10*V[victim.toLowerCase()]-V[attacker.toLowerCase()];if(m.ep)sc+=900;if(m.promotion)sc+=800;if(CENTER.has(m.to))sc+=40;if(EXT_CENTER.has(m.to))sc+=12;return sc}
const ordered=(s,ms)=>ms.slice().sort((a,b)=>moveOrderScore(s,b)-moveOrderScore(s,a));
const TIMEOUT={};let deadline=0,tt=new Map();function timeGuard(){if(performance.now()>deadline)throw TIMEOUT}
function quiescence(s,a,b,d=2){timeGuard();const stand=evalPos(s);if(d<=0)return stand;const caps=ordered(s,legal(s,s.turn).filter(m=>s.board[m.to]||m.ep||m.promotion));if(!caps.length)return stand;if(s.turn==='w'){let best=stand;if(best>=b)return best;a=Math.max(a,best);for(const m of caps){best=Math.max(best,quiescence(move(s,m),a,b,d-1));a=Math.max(a,best);if(a>=b)break}return best}else{let best=stand;if(best<=a)return best;b=Math.min(b,best);for(const m of caps){best=Math.min(best,quiescence(move(s,m),a,b,d-1));b=Math.min(b,best);if(a>=b)break}return best}}
function minimax(s,d,a,b){timeGuard();const key=positionKey(s)+'|'+d;const cached=tt.get(key);if(cached!==undefined)return cached;const ms=legal(s,s.turn);if(!ms.length)return check(s,s.turn)?(s.turn==='w'?-999999-d:999999+d):0;if(d===0)return quiescence(s,a,b,2);let best;if(s.turn==='w'){best=-Infinity;for(const m of ordered(s,ms)){best=Math.max(best,minimax(move(s,m),d-1,a,b));a=Math.max(a,best);if(b<=a)break}}else{best=Infinity;for(const m of ordered(s,ms)){best=Math.min(best,minimax(move(s,m),d-1,a,b));b=Math.min(b,best);if(b<=a)break}}tt.set(key,best);return best}
function ai(){const ms=ordered(st,legal(st,'b'));if(!ms.length)return null;const lv=+diff.value,bookChance=lv===1?.6:lv===2?.88:1,book=referenceMove(st);if(book&&Math.random()<bookChance)return book;const target=lv===1?2:lv===2?3:4,budget=lv===1?190:lv===2?650:1550;deadline=performance.now()+budget;tt=new Map();let bestMove=ms[0],bestScore=Infinity;for(let d=1;d<=target;d++){try{let roundMove=bestMove,roundScore=Infinity;for(const m of ms){timeGuard();const sc=minimax(move(st,m),d-1,-Infinity,Infinity);if(sc<roundScore){roundScore=sc;roundMove=m}}bestMove=roundMove;bestScore=roundScore}catch(e){if(e!==TIMEOUT)throw e;break}}if(lv===1){const ranked=[];for(const m of ms.slice(0,Math.min(6,ms.length))){try{ranked.push({m,sc:minimax(move(st,m),0,-Infinity,Infinity)})}catch{break}}const near=ranked.filter(x=>x.sc<=bestScore+85);if(near.length)return near[Math.floor(Math.random()*near.length)].m}return bestMove}
function render(){board.innerHTML='';const k=check(st,st.turn)?king(st,st.turn):-1;for(let i=0;i<64;i++){const q=document.createElement('button');q.type='button';q.className='square '+((row(i)+col(i))%2?'dark':'light');q.dataset.square=i;if(i===sel)q.classList.add('selected');if(last&&(i===last.from||i===last.to))q.classList.add('last');const lm=selMoves.find(m=>m.to===i);if(lm){if(st.board[i]||lm.ep)q.classList.add('capture');const d=document.createElement('span');d.className='moveDot';q.appendChild(d)}if(i===k)q.classList.add('check');const p=st.board[i];if(p){const z=document.createElement('span');z.className='piece '+(white(p)?'whitePiece':'blackPiece');z.textContent=S[p];q.appendChild(z)}if(col(i)===0){const z=document.createElement('span');z.className='coord r';z.textContent=8-row(i);q.appendChild(z)}if(row(i)===7){const z=document.createElement('span');z.className='coord f';z.textContent=F[col(i)];q.appendChild(z)}q.onclick=()=>clickSq(i);board.appendChild(q)}}
function clickSq(i){if(busy||over||st.turn!=='w')return;const p=st.board[i];if(sel===null){if(p&&side(p)==='w'){sel=i;selMoves=legal(st,'w').filter(m=>m.from===i);render()}return}const m=selMoves.find(m=>m.to===i);if(m){sel=null;selMoves=[];commit(m,false);return}if(p&&side(p)==='w'){sel=i;selMoves=legal(st,'w').filter(m=>m.from===i);render()}else{sel=null;selMoves=[];render()}}
function animate(m){return new Promise(resolve=>{const src=board.querySelector(`[data-square="${m.from}"] .piece`),tar=board.querySelector(`[data-square="${m.to}"] .piece`);if(!src){resolve();return}const br=board.getBoundingClientRect(),a=board.querySelector(`[data-square="${m.from}"]`).getBoundingClientRect(),z=board.querySelector(`[data-square="${m.to}"]`).getBoundingClientRect(),g=document.createElement('div'),piece=st.board[m.from];g.className='ghostMove '+(white(piece)?'whitePiece':'blackPiece');g.textContent=src.textContent;g.style.width=a.width+'px';g.style.height=a.height+'px';g.style.fontSize=getComputedStyle(src).fontSize;g.style.left=a.left-br.left+'px';g.style.top=a.top-br.top+'px';src.style.opacity='0';frame.classList.add('animating');board.appendChild(g);const squares=Math.hypot(row(m.to)-row(m.from),col(m.to)-col(m.from)),reduce=matchMedia('(prefers-reduced-motion: reduce)').matches,duration=reduce?1:Math.min(345,205+squares*22),dx=z.left-a.left,dy=z.top-a.top;let capAnim=null;if(tar)capAnim=tar.animate([{opacity:1,transform:'translate3d(0,-1%,0) scale(1)'},{opacity:.08,transform:'translate3d(0,-1%,0) scale(.84)'}],{duration:Math.max(1,duration*.72),easing:'ease-out',fill:'forwards'});const anim=g.animate([{transform:'translate3d(0,0,0) scale(1)'},{transform:`translate3d(${dx}px,${dy}px,0) scale(1.018)`},{transform:`translate3d(${dx}px,${dy}px,0) scale(1)`}],{duration,easing:'cubic-bezier(.22,.82,.2,1)',fill:'forwards'});anim.finished.catch(()=>{}).finally(()=>{capAnim?.cancel();g.remove();frame.classList.remove('animating');resolve()})})}
async function commit(m,bot){if(busy)return;busy=true;const before=st,n=notation(before,m),evalBefore=evalPos(before),fenBefore=fenString(before),ref=m.reference||null;await animate(m);st=move(before,m);last=m;const evalAfter=evalPos(st);hist.push({side:before.turn,n,uci:uci(m),fen_before:fenBefore,fen_after:fenString(st),eval_before_cp:evalBefore,eval_after_cp:evalAfter,reference:ref?{name:ref.name,eco:ref.eco,source:ref.source}:null});if(ref)session.reference_hits=(session.reference_hits||0)+1;render();panels();saveDraft();busy=false;const end=endCheck();if(!end&&!bot&&st.turn==='b')scheduleAI()}
function scheduleAI(){busy=true;thinking.classList.add('show');setTimeout(()=>{let m=null;try{m=ai()}finally{thinking.classList.remove('show');busy=false}if(m)commit(m,true)},260)}
function resultForWinner(winner){return winner==='w'?'1-0':'0-1'}
function endCheck(){const ms=legal(st,st.turn),ck=check(st,st.turn);if(ck){frame.classList.remove('ring');void frame.offsetWidth;frame.classList.add('ring');if(ms.length)showToast('CHECK',true)}if(!ms.length){over=true;if(ck){const winner=opp(st.turn);finalizeGame(resultForWinner(winner),'checkmate');showMate('CHECKMATE',(winner==='w'?'백':'흑')+' 승리')}else{finalizeGame('1/2-1/2','stalemate');showMate('STALEMATE','무승부')}return true}return false}
function showToast(t,d=false){clearTimeout(timer);toast.textContent=t;toast.classList.toggle('danger',d);toast.classList.add('show');timer=setTimeout(()=>toast.classList.remove('show'),1100)}
function showMate(t,s){$('mateTitle').textContent=t;$('mateSub').textContent=s;mate.classList.add('show');const r=frame.getBoundingClientRect();for(let i=0;i<18;i++){const x=document.createElement('i'),a=Math.random()*Math.PI*2,d=60+Math.random()*160;x.className='spark';x.style.left=r.left+r.width/2+'px';x.style.top=r.top+r.height/2+'px';x.style.setProperty('--dx',Math.cos(a)*d+'px');x.style.setProperty('--dy',Math.sin(a)*d+'px');if(i%3===1)x.style.background='var(--gold)';if(i%3===2)x.style.background='var(--accent2)';document.body.appendChild(x);setTimeout(()=>x.remove(),800)}setTimeout(()=>mate.classList.remove('show'),1500)}
function coach(){if(over)return{main:'한 판이 끝났습니다. 기보는 자동 저장되었습니다.',sub:'전체 백업 JSON을 남겨 두면 여러 판의 반복 약점을 나중에 함께 분석할 수 있습니다.'};if(check(st,st.turn))return{main:'체크입니다. 왕을 피하거나, 잡거나, 막는 수만 후보입니다.',sub:'체크 상황에서는 계획보다 합법적인 대응을 먼저 좁히세요.'};if(!hist.length)return{main:ST[cur].main,sub:ST[cur].sub};const lastRef=[...hist].reverse().find(x=>x.reference)?.reference;if(lastRef&&hist.length<18)return{main:`AI가 ${lastRef.name} 계열의 마스터 수순을 참고했습니다.`,sub:'오프닝에서는 중앙·전개·왕 안전이 동시에 좋아지는지 비교하세요.'};if(cur==='opening')return hist.length<6?{main:'중앙과 전개 속도를 계속 비교하세요.',sub:'퀸보다 나이트와 비숍의 자연스러운 칸을 먼저 확보하세요.'}:{main:'이제 왕의 안전과 룩 연결을 확인할 때입니다.',sub:'시작 칸에 남은 작은 기물이 있는지 훑어보세요.'};if(cur==='middlegame')return{main:'다음 수 전 강제수 세 종류를 다시 훑으세요.',sub:'체크 → 잡기 → 위협, 그리고 가장 나쁜 내 기물을 비교합니다.'};return{main:'한 칸의 템포를 돈처럼 아껴 쓰세요.',sub:'왕의 거리, 패스폰, 룩의 위치를 수마다 갱신하세요.'}}
function panels(){$('phasePill').textContent=ST[cur].label;$('statusText').textContent=ST[cur].status;$('turnText').textContent=st.turn==='w'?'백 차례':'흑 차례';$('turnDot').classList.toggle('black',st.turn==='b');$('moveCount').textContent=hist.length+' PLY';$('evalFill').style.width=Math.max(8,Math.min(92,50+evalPos(st)/30))+'%';const c=coach();$('coachMain').textContent=c.main;$('coachSub').textContent=c.sub;const ml=$('moveList');if(!hist.length){ml.innerHTML='<div class="empty">첫 수를 두면 이곳에 기보가 기록됩니다.</div>'}else{ml.innerHTML='';for(let i=0;i<hist.length;i+=2){const n=document.createElement('span');n.className='n';n.textContent=Math.floor(i/2)+1+'.';const w=document.createElement('span');w.className='mv';w.textContent=hist[i]?.n||'';const b=document.createElement('span');b.className='mv';b.textContent=hist[i+1]?.n||'…';ml.append(n,w,b)}ml.scrollTop=ml.scrollHeight}updateSaveUI()}
function gameDate(){const d=new Date();return `${d.getFullYear()}.${pad(d.getMonth()+1)}.${pad(d.getDate())}`}
function makePGN(result='*'){const tags=[`[Event "ForMyChess AI Arena"]`,`[Site "Browser"]`,`[Date "${gameDate()}"]`,`[White "skylark"]`,`[Black "ForMyChess AI ${diff.value}"]`,`[Result "${result}"]`,`[PlyCount "${hist.length}"]`];if(cur!=='opening')tags.push('[SetUp "1"]',`[FEN "${ST[cur].fen}"]`);const body=[];for(let i=0;i<hist.length;i+=2)body.push(`${Math.floor(i/2)+1}. ${hist[i]?.n||''}${hist[i+1]?` ${hist[i+1].n}`:''}`);return tags.join('\n')+'\n\n'+body.join(' ')+' '+result}
function newSession(){return{id:nowId(),started_at:new Date().toISOString(),phase:cur,difficulty:+diff.value,reference_hits:0,finalized:false}}
function getGames(){try{const x=JSON.parse(localStorage.getItem(SAVE_KEY)||'[]');return Array.isArray(x)?x:[]}catch{return[]}}
function setGames(g){try{localStorage.setItem(SAVE_KEY,JSON.stringify(g));return true}catch{return false}}
function buildRecord(result='*',termination='manual-export'){const ended=new Date().toISOString();return{schema_version:1,game_id:session?.id||nowId(),source:{kind:'browser-ai',event:'ForMyChess AI Arena',event_date:ended.slice(0,10),white:'skylark',black:`ForMyChess AI ${diff.value}`,result,ply_count:hist.length},player:{name:'skylark',color:'white'},pgn:makePGN(result),normalization_notes:['Auto-saved by the ForMyChess browser client. UCI move list and per-ply snapshots are retained for later engine verification.'],observations:[],game_summary:{phase:cur,difficulty:+diff.value,termination,started_at:session?.started_at||ended,ended_at:ended,reference_hits:session?.reference_hits||0,final_eval_cp:evalPos(st)},moves:hist.map((x,i)=>({ply:i+1,...x})),app:{name:'ForMyChess',save_version:1,reference_source:REF.source||null}}}
function finalizeGame(result='*',termination='reset'){if(!hist.length||session?.finalized)return null;const rec=buildRecord(result,termination),games=getGames(),i=games.findIndex(g=>g.game_id===rec.game_id);if(i>=0)games[i]=rec;else games.push(rec);setGames(games);session.finalized=true;localStorage.removeItem(DRAFT_KEY);updateSaveUI();showToast('기보 자동 저장 완료');return rec}
function saveDraft(){if(!hist.length)return;try{localStorage.setItem(DRAFT_KEY,JSON.stringify({phase:cur,difficulty:+diff.value,session,hist}));$('saveStatus').textContent='현재 대국 자동 저장 중'}catch{$('saveStatus').textContent='브라우저 저장 공간 확인 필요'}}
function restoreDraft(){let d;try{d=JSON.parse(localStorage.getItem(DRAFT_KEY)||'null')}catch{return false}if(!d||!ST[d.phase]||!Array.isArray(d.hist)||!d.hist.length)return false;cur=d.phase;stage.value=cur;diff.value=String(d.difficulty||2);st=fen(ST[cur].fen);const replay=[];for(const old of d.hist){const m=moveFromUci(st,old.uci);if(!m){localStorage.removeItem(DRAFT_KEY);return false}const before=st;st=move(st,m);replay.push({...old,side:before.turn})}hist=replay;last=hist.length?(()=>{const u=hist[hist.length-1].uci;return{from:idx(u.slice(0,2)),to:idx(u.slice(2,4))}})():null;session=d.session||newSession();session.finalized=false;sel=null;selMoves=[];over=false;busy=false;render();panels();showToast('이전 대국 복원');if(st.turn==='b')scheduleAI();return true}
function download(name,data){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function exportCurrent(){if(!hist.length){showToast('저장할 기보가 없습니다');return}const rec=buildRecord(over?(getGames().find(g=>g.game_id===session.id)?.source?.result||'*'):'*','manual-export');download(`${rec.game_id}.json`,rec);showToast('현재 기보 JSON 저장')}
function exportAll(){const games=getGames().slice();if(hist.length&&!session?.finalized){const curRec=buildRecord('*','in-progress-export'),i=games.findIndex(g=>g.game_id===curRec.game_id);if(i>=0)games[i]=curRec;else games.push(curRec)}if(!games.length){showToast('백업할 기보가 없습니다');return}download(`formychess-save-${new Date().toISOString().slice(0,10)}.json`,{format:'ForMyChess-save-bundle',version:1,exported_at:new Date().toISOString(),games});showToast(`${games.length}판 전체 백업 완료`)}
function updateSaveUI(){const n=getGames().length;$('saveCount').textContent=`${n} GAMES`;if(!hist.length)$('saveStatus').textContent=n?`확정 저장 ${n}판`:'브라우저 자동 저장 대기'}
function load(name,scroll=true,termination='stage-change'){if(hist.length&&!session?.finalized)finalizeGame('*',termination);cur=name;stage.value=name;st=fen(ST[name].fen);sel=null;selMoves=[];hist=[];last=null;over=false;busy=false;thinking.classList.remove('show');session=newSession();localStorage.removeItem(DRAFT_KEY);render();panels();if(scroll)$('arena').scrollIntoView({behavior:'smooth'});showToast(ST[name].label)}
function hero(){const e=$('heroBoard'),p=['r','n','b','q','k','b','n','r','p','p','p','p','p','p','p','p',...Array(32).fill(null),'P','P','P','P','P','P','P','P','R','N','B','Q','K','B','N','R'];p.forEach((x,i)=>{const q=document.createElement('div');q.className='heroSq '+((row(i)+col(i))%2?'dark':'light');q.textContent=x?S[x]:'';e.appendChild(q)})}
compileReferenceBook();document.querySelectorAll('.stageBtn').forEach(b=>b.onclick=()=>load(b.dataset.stage,true,'stage-change'));stage.onchange=()=>load(stage.value,false,'stage-change');diff.onchange=()=>{if(session)session.difficulty=+diff.value;saveDraft();showToast(`AI 난이도 ${diff.value}`)};$('reset').onclick=()=>load(cur,false,'reset');$('exportCurrent').onclick=exportCurrent;$('exportAll').onclick=exportAll;document.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName))return;const k=e.key.toLowerCase();if(k==='r')load(cur,false,'reset');if(k==='o')load('opening',true,'stage-change');if(k==='m')load('middlegame',true,'stage-change');if(k==='e')load('endgame',true,'stage-change')});window.addEventListener('beforeunload',saveDraft);hero();if(!restoreDraft())load('opening',false,'initial');
})();
